build:
	@g++ -std=c++11 Board.cpp CellTypes.cpp Direction.cpp Heuristics.cpp main.cpp pMove.cpp Solver.cpp Solution.cpp SearchNode.cpp *.h -o hw2

run1: build
	@./hw2 1 

run2: build
	@./hw2 2

run3: build
	@./hw2 3

